### ISSUE TITLE
Input validation failed

### ISSUE THREAD

**Issue by mikegillis677** [gmo/c2#1]
There are a bunch of jobs buried in ARC trying to be sent to C2, most of them saying "Input validation failed".  I'm going to guess that these are due to email address validation in C2 (an astonishing number of them are in the format foo.@example.com).  We should update C2 to handle these.
- [ ] Once the bug is fixed removed the increase sensu q limits

**Comment by justinmiller24** [comment]
@mikegillis677 Since we are handling invalid email addresses through the ARC autoresponder, is there any reason we need to have a 2nd layer of validation on C2, or can this be removed entirely?

**Comment by mikegillis677** [comment]
@justinmiller24 I'm not sure what the state of the codebase is, so I don't know if it can be entirely removed.  However, my intention was to thin the email address validation to a simple regex such as `/.+\@.+/`.  In other words, one character or more, an @ symbol, and one character or more.
